apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
spec:
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
      - name: cart-service
        image: trekkerone/cart-service
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "31672"
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  type: NodePort
  selector:
    app: cart-service
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32600